version: '3.8'

services:
  payload:
    image: shivram8080/acoblogs:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
